extends: relaxed

rules:
  line-length: disable
  indentation:
    level: error
    spaces: consistent
    indent-sequences: consistent

# The sample operators' YAML is what operator-sdk and controller-gen generate.
ignore: |
  **/node_modules/
  /bin/
  dist/
  samples/
